In [402]:
from  bs4 import BeautifulSoup as bs 
import pandas as pd
import requests 
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import warnings

# Ignore all warnings
warnings.filterwarnings('ignore')

In [406]:
def get_summery_data(i,j):
    url = f"https://results.eci.gov.in/ResultAcGenMay2026/Constituencywise{j}.htm"
    browser = webdriver.Chrome("./chromedriver")
    browser.get(url)
    


    soup = bs(browser.page_source,"html.parser")
    table = soup.find('table')
    if not table:
        print("No table found on the page.")


    headers = []
    header_row = table.find('tr')
    if header_row:
        headers = [th.get_text(strip=True) for th in header_row.find_all(['th', 'td'])]

    
    rows_data = []
    for row in table.find_all('tr')[1:]:  
        cols = row.find_all(['td', 'th'])
        cols_text = [col.get_text(strip=True) for col in cols]
        if cols_text:  
            rows_data.append(cols_text)

  
    headers.append('Constituency')
    
    rows_data = rows_data[:-1]
    for x in rows_data:
        t = j.replace('S22',"")
        x.append(f'{t} - {i}')
    df = pd.DataFrame(rows_data[:-1], columns=headers)
    return df

In [407]:
wb_numbs=['S2512','S25102','S25181','S25200','S25280','S25281','S25101','S25273','S2599','S2594','S25240','S25180','S2572','S2554','S25191','S25239','S25169','S25161','S2539','S25238','S2596','S2595','S25252','S25283','S25113','S25119','S25260','S25266','S25253','S25108','S25140','S25137','S25128','S25124','S25125','S25154','S25153','S2571','S25164','S25159','S25214','S2562','S25148','S2569','S25267','S25105','S25116','S25103','S25237','S25146','S25255','S25286','S25156','S2567','S25138','S25139','S2591','S2531','S25187','S2545','S25189','S25211','S25194','S25232','S2582','S25248','S2528','S25162','S25190','S254','S253','S2519','S25219','S2523','S25230','S25229','S25120','S25197','S2515','S25143','S257','S25184','S2575','S25284','S25114','S25110','S25277','S25276','S25218','S2551','S25163','S2513','S25144','S2555','S2597','S25274','S2541','S25233','S2544','S25231','S2530','S25201','S25221','S25127','S2543','S25100','S25209','S25292','S2573','S2593','S25196','S2542','S2546','S25121','S2533','S25126','S25173','S25171','S25170','S25257','S2529','S2536','S25150','S25183','S25106','S2576','S2517','S25262','S25279','S25195','S2558','S25136','S25222','S25165','S25241','S25131','S2511','S2534','S2580','S2522','S25264','S2592','S25112','S2568','S25216','S25213','S2532','S2577','S25149','S25244','S25168','S25256','S25270','S25223','S25235','S25271','S25202','S25259','S25228','S25224','S25109','S2566','S25215','S25158','S2588','S2585','S2583','S25133','S25129','S25282','S2538','S2510','S2524','S2537','S25288','S2561','S2514','S25118','S25142','S25141','S25155','S25208','S2520','S2547','S2550','S25243','S25135','S25272','S2549','S25167','S252','S2525','S2516','S25290','S25236','S251','S25265','S25157','S25122','S25263','S2552','S25206','S25294','S2564','S2584','S2565','S2521','S25104','S2581','S25293','S25207','S25210','S25287','S25225','S258','S25220','S25107','S2574','S25254','S2579','S25175','S25275','S25192','S25111','S25205','S25204','S25245','S25212','S25130','S2527','S25227','S25268','S25269','S25199','S25242','S2559','S25246','S25134','S2535','S25261','S25250','S25117','S25115','S2518','S25217','S25291','S2590','S2587','S2589','S25249','S25278','S2563','S25160','S2548','S2570','S25226','S25132','S2560','S25289','S25234','S25247','S2556','S25123','S25174','S2586','S25193','S25145','S25172','S25166','S25179','S2526','S25188','S256','S255','S25258','S25147','S25151','S25186','S2553','S25285','S2557','S2598','S25251','S25203','S2540','S25198','S2578','S25152','S259','S25182','S25178','S25176','S25177','S25185']
wb_nms = ['ALIPURDUARS','AMDANGA','AMTA','ARAMBAG','ASANSOL DAKSHIN','ASANSOL UTTAR','ASHOKNAGAR','AUSGRAM','BADURIA','BAGDA','BAGHMUNDI','BAGNAN','BAHARAMPUR','BAISNABNAGAR','BALAGARH','BALARAMPUR','BALLY','BALLYGUNGE','BALURGHAT','BANDWAN','BANGAON DAKSHIN','BANGAON UTTAR','BANKURA','BARABANI','BARANAGAR','BARASAT','BARDHAMAN DAKSHIN','BARDHAMAN UTTAR','BARJORA','BARRACKPUR','BARUIPUR PASCHIM','BARUIPUR PURBA','BASANTI','BASIRHAT DAKSHIN','BASIRHAT UTTAR','BEHALA PASCHIM','BEHALA PURBA','BELDANGA','BELEGHATA','BHABANIPUR','BHAGABANPUR','BHAGAWANGOLA','BHANGAR','BHARATPUR','BHATAR','BHATPARA','BIDHANNAGAR','BIJPUR','BINPUR','BISHNUPUR','BISHNUPUR','BOLPUR','BUDGE BUDGE','BURWAN','CANNING PASCHIM','CANNING PURBA','CHAKDAHA','CHAKULIA','CHAMPDANI','CHANCHAL','CHANDANNAGAR','CHANDIPUR','CHANDITALA','CHANDRAKONA','CHAPRA','CHHATNA','CHOPRA','CHOWRANGEE','CHUNCHURA','COOCHBEHAR DAKSHIN','COOCHBEHAR UTTAR','DABGRAM','DANTAN','DARJEELING','DASPUR','DEBRA','DEGANGA','DHANEKHALI','DHUPGURI','DIAMOND HARBOUR','DINHATA','DOMJUR','DOMKAL','DUBRAJPUR','DUM DUM','DUM DUM UTTAR','DURGAPUR PASCHIM','DURGAPUR PURBA','EGRA','ENGLISH BAZAR','ENTALLY','FALAKATA','FALTA','FARAKKA','GAIGHATA','GALSI','GANGARAMPUR','GARBETA','GAZOLE','GHATAL','GOALPOKHAR','GOGHAT','GOPIBALLAVPUR','GOSABA','HABIBPUR','HABRA','HALDIA','HANSAN','HARIHARPARA','HARINGHATA','HARIPAL','HARIRAMPUR','HARISCHANDRAPUR','HAROA','HEMTABAD','HINGALGANJ','HOWRAH DAKSHIN','HOWRAH MADHYA','HOWRAH UTTAR','INDUS','ISLAMPUR','ITAHAR','JADAVPUR','JAGATBALLAVPUR','JAGATDAL','JALANGI','JALPAIGURI','JAMALPUR','JAMURIA','JANGIPARA','JANGIPUR','JAYNAGAR','JHARGRAM','JORASANKO','JOYPUR','KAKDWIP','KALCHINI','KALIAGANJ','KALIGANJ','KALIMPONG','KALNA','KALYANI','KAMARHATI','KANDI','KANTHI DAKSHIN','KANTHI UTTAR','KARANDIGHI','KARIMPUR','KASBA','KASHIPUR','KASHIPUR','KATULPUR','KATWA','KESHIARY','KESHPUR','KETUGRAM','KHANAKUL','KHANDAGHOSH','KHARAGPUR','KHARAGPUR SADAR','KHARDAHA','KHARGRAM','KHEJURI','KOLKATA PORT','KRISHNAGANJ','KRISHNANAGAR DAKSHIN','KRISHNANAGAR UTTAR','KULPI','KULTALI','KULTI','KUMARGANJ','KUMARGRAM','KURSEONG','KUSHMANDI','LABPUR','LALGOLA','MADARIHAT','MADHYAMGRAM','MAGRAHAT PASCHIM','MAGRAHAT PURBA','MAHESHTALA','MAHISADAL','MAL','MALATIPUR','MALDAHA','MANBAZAR','MANDIRBAZAR','MANGALKOT','MANIKCHAK','MANIKTALA','MATHABHANGA','MATIGARA','MAYNAGURI','MAYURESWAR','MEDINIPUR','MEKLIGANJ','MEMARI','METIABURUZ','MINAKHAN','MONTESWAR','MOTHABARI','MOYNA','MURARAI','MURSHIDABAD','NABADWIP','NABAGRAM','NAGRAKATA','NAIHATI','NAKASHIPARA','NALHATI','NANDAKUMAR','NANDIGRAM','NANOOR','NARAYANGARH','NATABARI','NAYAGRAM','NOAPARA','NOWDA','ONDA','PALASHIPARA','PANCHLA','PANDABESWAR','PANDUA','PANIHATI','PANSKURA PASCHIM','PANSKURA PURBA','PARA','PATASHPUR','PATHARPRATIMA','PHANSIDEWA','PINGLA','PURBASTHALI DAKSHIN','PURBASTHALI UTTAR','PURSURAH','PURULIA','RAGHUNATHGANJ','RAGHUNATHPUR','RAIDIGHI','RAIGANJ','RAINA','RAIPUR','RAJARHAT GOPALPUR','RAJARHAT NEW TOWN','RAJGANJ','RAMNAGAR','RAMPURHAT','RANAGHAT DAKSHIN','RANAGHAT UTTAR PASCHIM','RANAGHAT UTTAR PURBA','RANIBANDH','RANIGANJ','RANINAGAR','RASHBEHARI','RATUA','REJINAGAR','SABANG','SAGAR','SAGARDIGHI','SAINTHIA','SALBONI','SALTORA','SAMSERGANJ','SANDESHKHALI','SANKRAIL','SANTIPUR','SAPTAGRAM','SATGACHHIA','SHIBPUR','SHYAMPUKUR','SHYAMPUR','SILIGURI','SINGUR','SITAI','SITALKUCHI','SONAMUKHI','SONARPUR DAKSHIN','SONARPUR UTTAR','SREERAMPUR','SUJAPUR','SURI','SUTI','SWARUPNAGAR','TALDANGRA','TAMLUK','TAPAN','TARAKESWAR','TEHATTA','TOLLYGANJ','TUFANGANJ','UDAYNARAYANPUR','ULUBERIA DAKSHIN','ULUBERIA PURBA','ULUBERIA UTTAR','UTTARPARA']

In [408]:
numbs=['S2228','S22182','S22223','S22225','S228','S2248','S2244','S22198','S2221','S22105','S2238','S2267','S22183','S22134','S2242','S22149','S22207','S22129','S2282','S226','S22112','S2252','S22104','S22107','S22157','S22200','S2232','S2262','S2219','S2268','S2234','S22158','S22118','S22120','S22231','S22110','S22155','S22201','S22101','S2259','S22132','S2211','S2286','S2216','S2298','S2299','S22178','S2281','S2270','S22106','S22109','S2246','S221','S2218','S2261','S2255','S22150','S2249','S22221','S2265','S2280','S2237','S22102','S22229','S22184','S22135','S2240','S22159','S22117','S22234','S2264','S2245','S22164','S22122','S2213','S22218','S2253','S22136','S22137','S2297','S22171','S22148','S22156','S22143','S22126','S229','S22193','S22189','S22191','S22192','S22194','S2235','S227','S2271','S22144','S22187','S22138','S22167','S22161','S22188','S22111','S2285','S22100','S22212','S22145','S2225','S22163','S22230','S2294','S22227','S22169','S22131','S22153','S22130','S22128','S2284','S22175','S22217','S22232','S2257','S22127','S22226','S22115','S2230','S22154','S22172','S2260','S22209','S2295','S22176','S2258','S22147','S2212','S22177','S22199','S22103','S22123','S2266','S222','S22162','S225','S22180','S22228','S22202','S22211','S2241','S2292','S2278','S2217','S2223','S2289','S2290','S2288','S22219','S2279','S2287','S22204','S2293','S22190','S2239','S2227','S22121','S22160','S22186','S22205','S2229','S22139','S22216','S22203','S22116','S2231','S22222','S2256','S22174','S2215','S22196','S22181','S22195','S2233','S22166','S22173','S224','S22168','S22142','S22170','S2210','S2224','S22119','S22214','S2220','S22146','S2272','S22215','S2296','S22141','S22140','S22208','S2276','S22224','S2250','S22185','S22113','S22114','S223','S22210','S2263','S22151','S22108','S22125','S2277','S22197','S2251','S2236','S22124','S2269','S2247','S2273','S22220','S22165','S22133','S2291','S2226','S2243','S2254','S2275','S22213','S22233','S2214','S2274','S22179','S22206','S2222','S22152','S2283']
nms = ['ALANDUR','ALANGUDI','ALANGULAM','AMBASAMUDRAM','AMBATTUR','AMBUR','ANAIKATTU','ANDIPATTI','ANNA NAGAR','ANTHIYUR','ARAKKONAM','ARANI','ARANTHANGI','ARAVAKURICHI','ARCOT','ARIYALUR','ARUPPUKKOTTAI','ATHOOR','ATTUR','AVADI','AVANASHI','BARGUR','BHAVANI','BHAVANISAGAR','BHUVANAGIRI','BODINAYAKANUR','CHENGALPATTU','CHENGAM','CHEPAUK','CHEYYAR','CHEYYUR','CHIDAMBARAM','COIMBATORE (NORTH)','COIMBATORE (SOUTH)','COLACHAL','COONOOR','CUDDALORE','CUMBUM','DHARAPURAM','DHARMAPURI','DINDIGUL','DR.RADHAKRISHNAN NAGAR','EDAPPADI','EGMORE','ERODE (EAST)','ERODE (WEST)','GANDHARVAKOTTAI','GANGAVALLI','GINGEE','GOBICHETTIPALAYAM','GUDALUR','GUDIYATTAM','GUMMIDIPOONDI','HARBOUR','HARUR','HOSUR','JAYANKONDAM','JOLARPET','KADAYANALLUR','KALASAPAKKAM','KALLAKURICHI','KANCHEEPURAM','KANGAYAM','KANNIYAKUMARI','KARAIKUDI','KARUR','KATPADI','KATTUMANNARKOIL','KAVUNDAMPALAYAM','KILLIYOOR','KILPENNATHUR','KILVAITHINANKUPPAM','KILVELUR','KINATHUKADAVU','KOLATHUR','KOVILPATTI','KRISHNAGIRI','KRISHNARAYAPURAM','KULITHALAI','KUMARAPALAYAM','KUMBAKONAM','KUNNAM','KURINJIPADI','LALGUDI','MADATHUKULAM','MADAVARAM','MADURAI CENTRAL','MADURAI EAST','MADURAI NORTH','MADURAI SOUTH','MADURAI WEST','MADURANTAKAM','MADURAVOYAL','MAILAM','MANACHANALLUR','MANAMADURAI','MANAPPARAI','MANNARGUDI','MAYILADUTHURAI','MELUR','METTUPPALAYAM','METTUR','MODAKKURICHI','MUDHUKULATHUR','MUSIRI','MYLAPORE','NAGAPATTINAM','NAGERCOIL','NAMAKKAL','NANGUNERI','NANNILAM','NATHAM','NEYVELI','NILAKKOTTAI','ODDANCHATRAM','OMALUR','ORATHANADU','OTTAPIDARAM','PADMANABHAPURAM','PALACODU','PALANI','PALAYAMKOTTAI','PALLADAM','PALLAVARAM','PANRUTI','PAPANASAM','PAPPIREDDIPATTI','PARAMAKUDI','PARAMATHI','PATTUKKOTTAI','PENNAGARAM','PERAMBALUR','PERAMBUR','PERAVURANI','PERIYAKULAM','PERUNDURAI','POLLACHI','POLUR','PONNERI','POOMPUHAR','POONAMALLEE','PUDUKKOTTAI','RADHAPURAM','RAJAPALAYAM','RAMANATHAPURAM','RANIPET','RASIPURAM','RISHIVANDIYAM','ROYAPURAM','SAIDAPET','SALEM (NORTH)','SALEM (SOUTH)','SALEM (WEST)','SANKARANKOVIL','SANKARAPURAM','SANKARI','SATTUR','SENTHAMANGALAM','SHOLAVANDAN','SHOLINGUR','SHOZHINGANALLUR','SINGANALLUR','SIRKAZHI','SIVAGANGA','SIVAKASI','SRIPERUMBUDUR','SRIRANGAM','SRIVAIKUNTAM','SRIVILLIPUTHUR','SULUR','TAMBARAM','TENKASI','THALLI','THANJAVUR','THIRU','THIRUMANGALAM','THIRUMAYAM','THIRUPARANKUNDRAM','THIRUPORUR','THIRUTHURAIPOONDI','THIRUVAIYARU','THIRUVALLUR','THIRUVARUR','THIRUVERUMBUR','THIRUVIDAIMARUDUR','THIRUVOTTIYUR','THIYAGARAYANAGAR','THONDAMUTHUR','THOOTHUKKUDI','THOUSAND LIGHTS','THURAIYUR','TINDIVANAM','TIRUCHENDUR','TIRUCHENGODU','TIRUCHIRAPPALLI (EAST)','TIRUCHIRAPPALLI (WEST)','TIRUCHULI','TIRUKKOYILUR','TIRUNELVELI','TIRUPPATTUR','TIRUPPATTUR','TIRUPPUR (NORTH)','TIRUPPUR (SOUTH)','TIRUTTANI','TIRUVADANAI','TIRUVANNAMALAI','TITTAKUDI','UDHAGAMANDALAM','UDUMALAIPETTAI','ULUNDURPETTAI','USILAMPATTI','UTHANGARAI','UTHIRAMERUR','VALPARAI','VANDAVASI','VANIYAMBADI','VANUR','VASUDEVANALLUR','VEDARANYAM','VEDASANDUR','VEERAPANDI','VELACHERY','VELLORE','VEPPANAHALLI','VIKRAVANDI','VILATHIKULAM','VILAVANCODE','VILLIVAKKAM','VILUPPURAM','VIRALIMALAI','VIRUDHUNAGAR','VIRUGAMPAKKAM','VRIDDHACHALAM','YERCAUD']

In [409]:
# numbs = ['S11115','S11104','S1160','S1176','S11105','S1175','S11113','S11102','S11136','S11128','S1110','S1125','S1129','S11122','S1172','S1199','S11126','S11117','S1161','S11110','S11103','S11129','S1158','S1188','S1112','S1126','S1182','S11125','S1134','S1196','S1163','S11107','S1191','S119','S1170','S1194','S1169','S1177','S117','S1119','S114','S11100','S1111','S11116','S112','S11138','S11108','S11132','S1180','S1173','S1131','S11124','S1133','S1153','S11114','S1187','S1146','S11119','S1197','S11139','S1127','S1128','S11123','S1130','S1162','S1184','S11118','S1114','S11106','S1121','S1155','S1140','S1164','S1117','S1137','S111','S1139','S1154','S1115','S11109','S1186','S1122','S1168','S11130','S1159','S11135','S11140','S1135','S1166','S1152','S1193','S1156','S11137','S1178','S11120','S1150','S116','S1192','S1124','S1116','S1138','S1174','S1185','S1148','S11101','S1171','S11121','S1198','S1123','S11112','S1151','S1118','S118','S1144','S1157','S1113','S1147','S11111','S1132','S11134','S1190','S1183','S1181','S1167','S1149','S1145','S1143','S115','S113','S1189','S1120','S1195','S1142','S11131','S11127','S11133','S1141','S1179','S1165','S1136']
# nms=['ADOOR','ALAPPUZHA','ALATHUR','ALUVA','AMBALAPPUZHA','ANGAMALY','ARANMULA','AROOR','ARUVIKKARA','ATTINGAL','AZHIKODE','BALUSSERI','BEYPORE','CHADAYAMANGALAM','CHALAKUDY','CHANGANASSERY','CHATHANNOOR','CHAVARA','CHELAKKARA','CHENGANNUR','CHERTHALA','CHIRAYINKEEZHU','CHITTUR','DEVIKULAM','DHARMADAM','ELATHUR','ERANAKULAM','ERAVIPURAM','ERNAD','ETTUMANOOR','GURUVAYOOR','HARIPAD','IDUKKI','IRIKKUR','IRINJALAKUDA','KADUTHURUTHY','KAIPAMANGALAM','KALAMASSERY','KALLIASSERI','KALPETTA','KANHANGAD','KANJIRAPPALLY','KANNUR','KARUNAGAPPALLY','KASARAGOD','KATTAKKADA','KAYAMKULAM','KAZHAKOOTTAM','KOCHI','KODUNGALLUR','KODUVALLY','KOLLAM','KONDOTTY','KONGAD','KONNI','KOTHAMANGALAM','KOTTAKKAL','KOTTARAKKARA','KOTTAYAM','KOVALAM','KOZHIKODE NORTH','KOZHIKODE SOUTH','KUNDARA','KUNNAMANGALAM','KUNNAMKULAM','KUNNATHUNAD','KUNNATHUR','KUTHUPARAMBA','KUTTANAD','KUTTIADI','MALAMPUZHA','MALAPPURAM','MANALUR','MANANTHAVADY','MANJERI','MANJESHWAR','MANKADA','MANNARKKAD','MATTANNUR','MAVELIKKARA','MUVATTUPUZHA','NADAPURAM','NATTIKA','NEDUMANGAD','NEMMARA','NEMOM','NEYYATTINKARA','NILAMBUR','OLLUR','OTTAPPALAM','PALA','PALAKKAD','PARASSALA','PARAVUR','PATHANAPURAM','PATTAMBI','PAYYANNUR','PEERUMADE','PERAMBRA','PERAVOOR','PERINTHALMANNA','PERUMBAVOOR','PIRAVOM','PONNANI','POONJAR','PUDUKKAD','PUNALUR','PUTHUPPALLY','QUILANDY','RANNI','SHORNUR','SULTHANBATHERY','TALIPARAMBA','TANUR','TARUR','THALASSERY','THAVANUR','THIRUVALLA','THIRUVAMBADI','THIRUVANANTHAPURAM','THODUPUZHA','THRIKKAKARA','THRIPUNITHURA','THRISSUR','THRITHALA','TIRUR','TIRURANGADI','TRIKARIPUR','UDMA','UDUMBANCHOLA','VADAKARA','VAIKOM','VALLIKUNNU','VAMANAPURAM','VARKALA','VATTIYOORKAVU','VENGARA','VYPEN','WADAKKANCHERY','WANDOOR']

In [410]:
# numbs = ['S0316','S03122','S03112','S0326','S0342','S034','S0366','S0359','S0338','S0324','S0371','S0345','S0321','S0373','S0320','S0310','S0362','S039','S0370','S03108','S03105','S0328','S0318','S03117','S0387','S0327','S0323','S0351','S0395','S03104','S0377','S0365','S0378','S0355','S03120','S038','S0388','S0384','S0334','S03110','S0333','S0382','S032','S0315','S0390','S037','S0314','S0313','S0372','S03103','S036','S0344','S031','S0336','S03113','S03121','S0330','S0363','S03109','S0352','S0312','S0337','S0380','S03100','S0357','S0332','S03123','S03124','S03116','S0389','S03106','S033','S0353','S0376','S03114','S0364','S0394','S0398','S0385','S0341','S0322','S0350','S0311','S0383','S03101','S0347','S0354','S0369','S0360','S0392','S0339','S0397','S0335','S0375','S0325','S0329','S035','S03125','S0361','S03126','S0368','S0331','S03111','S0374','S0356','S0381','S0358','S03107','S0396','S0319','S03118','S0349','S0379','S03119','S0393','S0317','S0343','S0348','S0399','S0367','S0340','S0391','S0386','S03102','S0346','S03115']
# nms = ['ABHAYAPURI','ALGAPUR','AMRI','BAJALI','BAKSA','BAOKHUNGRI','BARCHALLA','BARHAMPUR','BARKHETRI','BARPETA','BEHALI','BHERGAON','BHOWANIPUR','BIHPURIA','BIJNI','BILASIPARA','BINNAKANDI','BIRSING JARUA','BISWANATH','BOKAJAN','BOKAKHAT','BOKO','BONGAIGAON','BORKHOLA','CHABUA','CHAMARIA','CHENGA','DALGAON','DEMOW','DERGAON','DHAKUAKHANA','DHEKIAJULI','DHEMAJI','DHING','DHOLAI','DHUBRI','DIBRUGARH','DIGBOI','DIMORIA','DIPHU','DISPUR','DOOMDOOMA','DOTMA','DUDHNAI','DULIAJAN','GAURIPUR','GOALPARA EAST','GOALPARA WEST','GOHPUR','GOLAGHAT','GOLAKGANJ','GORESWAR','GOSSAIGAON','GUWAHATI CENTRAL','HAFLONG','HAILAKANDI','HAJO','HOJAI','HOWRAGHAT','JAGIROAD','JALESHWAR','JALUKBARI','JONAI','JORHAT','KALIABOR','KAMALPUR','KARIMGANJ NORTH','KARIMGANJ SOUTH','KATIGORAH','KHOWANG','KHUMTAI','KOKRAJHAR','LAHARIGHAT','LAKHIMPUR','LAKHIPUR','LUMDING','MAHMORA','MAJULI','MAKUM','MANAS','MANDIA','MANGALDAI','MANKACHAR','MARGHERITA','MARIANI','MAZBAT','MORIGAON','NADUAR','NAGAON','NAHARKATIA','NALBARI','NAZIRA','NEW GUWAHATI','NOWBOICHA','PAKABETBARI','PALASBARI','PARBATJHORA','PATHARKANDI','RAHA','RAM KRISHNA NAGAR','RANGAPARA','RANGIA','RONGKHANG','RONGONADI','RUPAHIHAT','SADIYA','SAMAGURI','SARUPATHAR','SIBSAGAR','SIDLI CHIRANG','SILCHAR','SIPAJHAR','SISSIBARGAON','SONAI','SONARI','SRIJANGRAM','TAMULPUR','TANGLA','TEOK','TEZPUR','TIHU','TINGKHONG','TINSUKIA','TITABOR','UDALGURI','UDHARBOND']

In [411]:
# numbs = ['U0719','U0723','U0721','U078','U077','U0712','U0710','U0726','U0727','U0711','U0729','U0720','U074','U071','U0718','U0713','U0724','U0717','U0728','U0722','U0716','U0715','U073','U076','U0714','U079','U072','U0725','U075','U0730']

# nms=['ARIANKUPPAM','BAHOUR','EMBALAM','INDIRA NAGAR','KADIRGAMAM','KALAPET','KAMARAJ NAGAR','KARAIKAL NORTH','KARAIKAL SOUTH','LAWSPET','MAHE','MANAVELY','MANGALAM','MANNADIPET','MUDALIARPET','MUTHIALPET','NEDUNGADU','NELLITHOPE','NERAVY','NETTAPAKKAM','ORLEAMPETH','OUPALAM','OUSSUDU','OZHUKARAI','RAJ BHAVAN','THATTANCHAVADY','THIRUBHUVANAI','THIRUNALLAR','VILLIANUR','YANAM']

In [412]:
dfs = []
c = 0
for q,w in zip(nms,numbs):
    try:
        dfs.append(get_summery_data(i=q,j=w))
        c+=1
        print(c)
    except:
        print(f"error{c}")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
No table found on the page.
error203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233

In [413]:
combined_df = pd.concat(dfs, ignore_index=True)
combined_df.shape
combined_df.to_csv('result_summary.csv', index=False)

In [414]:
combined_df.head()

,S.N.,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes,Constituency
0,1,T.M.ANBARASAN,Dravida Munnetra Kazhagam,81642,954,82596,31.58,28 - ALANDUR
1,2,S.SARAVANAN,All India Anna Dravida Munnetra Kazhagam,51652,591,52243,19.97,28 - ALANDUR
2,3,Y.G.MAHALAKSHMI,Naam Tamilar Katchi,10346,59,10405,3.98,28 - ALANDUR
3,4,J.AGNI SELVARASU,Naadaalum Makkal Katchi,230,3,233,0.09,28 - ALANDUR
4,5,ARAVIND CHANDRASEKAR,Indhu Dravida Makkal Katchi,76,1,77,0.03,28 - ALANDUR

In [415]:
combined_df.tail()

,S.N.,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes,Constituency
4005,9,KALIYAPPAN. A,Independent,123,0,123,0.05,83 - YERCAUD
4006,10,THANGADURAI. N,Independent,291,3,294,0.12,83 - YERCAUD
4007,11,PAZHANIVEL. K,Independent,303,0,303,0.12,83 - YERCAUD
4008,12,VIJAYAKUMAR. N,Independent,210,1,211,0.08,83 - YERCAUD
4009,13,VENKATESAN. S,Independent,510,3,513,0.2,83 - YERCAUD

In [416]:
def get_round_wise_counting(q,w):
    records=[]
    url = f"https://results.eci.gov.in/ResultAcGenMay2026/Roundwise{w}.htm"
    browser = webdriver.Chrome("./chromedriver")
    browser.get(url)
    soup = bs(browser.page_source,"html.parser")
    table = soup.find_all('div',class_='custom-table tabcontent')

    t = w.replace('S22',"")
    for round_num,i in enumerate(table):
        tbody = i.find('tbody')
        for tr in tbody.find_all("tr"):

            cells = [td.get_text(strip=True) for td in tr.find_all("td")]
           
            if len(cells) < 5:
                continue  # skip malformed / footer rows

            candidate, party, votes_prev, votes_current, votes_total = cells[:5]

            records.append({
                "round":         round_num+1,
                "candidate":     candidate,
                "party":         party,
                "votes_prev":    votes_prev.replace(",", ""),
                "votes_current": votes_current.replace(",", ""),
                "votes_total":   votes_total.replace(",", ""),
                "Constituency": f'{t} - {q}'
            })      
    df = pd.DataFrame.from_dict(records)
    return df

In [417]:
dfs = []
c = 1
for q,w in zip(nms,numbs):
    try:
        dfs.append(get_round_wise_counting(q,w))
        print(c)
        c+=1
    except:
        print(f'error{c}')

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234

In [418]:
combined_df = pd.concat(dfs, ignore_index=True)
combined_df.shape
combined_df.to_csv('result_round_wise_counting.csv', index=False)

In [419]:
combined_df.head()

,round,candidate,party,votes_prev,votes_current,votes_total,Constituency
0,1,T.M.ANBARASAN,Dravida Munnetra Kazhagam,0,2465,2465,28 - ALANDUR
1,1,S.SARAVANAN,All India Anna Dravida Munnetra Kazhagam,0,1621,1621,28 - ALANDUR
2,1,Y.G.MAHALAKSHMI,Naam Tamilar Katchi,0,337,337,28 - ALANDUR
3,1,J.AGNI SELVARASU,Naadaalum Makkal Katchi,0,8,8,28 - ALANDUR
4,1,ARAVIND CHANDRASEKAR,Indhu Dravida Makkal Katchi,0,4,4,28 - ALANDUR

In [420]:
combined_df.tail()

,round,candidate,party,votes_prev,votes_current,votes_total,Constituency
101456,25,THANGADURAI. N,Independent,289,2,291,83 - YERCAUD
101457,25,PAZHANIVEL. K,Independent,301,2,303,83 - YERCAUD
101458,25,VIJAYAKUMAR. N,Independent,204,6,210,83 - YERCAUD
101459,25,VENKATESAN. S,Independent,508,2,510,83 - YERCAUD
101460,25,NOTA,None of the Above,1226,5,1231,83 - YERCAUD